name: 修改插件配置项
title: "plugin: {name}"
description: 修改插件测试时的配置项
labels: ["Plugin", "Config"]
body:
  - type: input
    id: pypi
    attributes:
      label: PyPI 项目名
      description: PyPI 项目名
      placeholder: e.g. nonebot-plugin-xxx
    validations:
      required: true

  - type: input
    id: module
    attributes:
      label: 插件 import 包名
      description: 插件 import 包名
      placeholder: e.g. nonebot_plugin_xxx
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: 插件配置项
      description: 插件配置项
      render: dotenv
      placeholder: |
        # e.g.
        # KEY=VALUE
        # KEY2=VALUE2
